var express = require('express');
var router = express.Router();
const contactController = require('../src/Controller/contactController');
const cartController = require('../src/Controller/cartController');
const myaccountController = require('../src/Controller/myaccountController');
const loginController = require('../src/Controller/loginController');
const productdetailController = require('../src/Controller/productdetailController');
const constantController = require('../src/Controller/constantController');
const productlistController = require('../src/Controller/productlistController');
const checkoutController = require('../src/Controller/checkoutController');
const { route } = require('./users');
/* GET home page. */
router.get('/',constantController.index);
router.get('/contact',contactController.index);
router.post('/save-contact',contactController.store);
router.get('/cart',cartController.index);
router.post('/cart-save',cartController.store);
router.post('/cart-update',cartController.update);
router.post('/cart-delete',cartController.delete);
router.get('/myaccount',myaccountController.index);
router.get('/login',loginController.index);
router.post('/login-save',loginController.store);
router.post('/signin',loginController.signin);
router.get('/productdetail',productdetailController.index);
router.get('/store-product',productlistController.productStore);
router.post('/save-products', productlistController.store);
router.get('/products',productlistController.index);
router.get('/checkouts',checkoutController.index);
router.post('/checkout-save',checkoutController.store);
module.exports = router;
